module.exports=(function(){
    this.시세=require('./price/price.js')
    this.거래원=require('./exchange/exchange.js')
    this.투자정보=require('./tradeinfo/tradeinfo.js')
    this.프로그램=require('./program/program.js')
    this.투자자=require('./investor/investor.js')
    this.외인기관=require('./foreigner/foreigner.js')
    this.ELW=require('./elw/elw.js')
    this.ETF=require('./etf/etf.js')
    this.섹터=require('./sector/sector.js')
    this.종목검색=require('./search/search.js')
    this.상위종목=require('./high/high.js')
    this.차트=require('./chart/chart.js')
    this.기타=require('./other/other.js')
    this.계좌=require('./account/account.js')
    this.주문=require('./order/order.js')
    this.실시간=require('./realtime/realtime.js')
    return this;
})();