const lib=require("k-lib-im");
/**
 * @typedef {Object} t1601 [주식] 투자자 - 투자자별종합
 * @property {string} rsp_cd tr 코드
 * @property {string} rsp_msg tr 메세지
 * @property {t1601_OutBlock1} t1601OutBlock1
 * @property {t1601_OutBlock2} t1601OutBlock2
 * @property {t1601_OutBlock3} t1601OutBlock3
 * @property {t1601_OutBlock4} t1601OutBlock4
 * @property {t1601_OutBlock5} t1601OutBlock5
 * @property {t1601_OutBlock6} t1601OutBlock6
 */
/**
 * @typedef {Object} t1601_OutBlock1 [주식] 투자자 - 투자자별종합 
 * @property {string} tjjcode_08 개인투자자코드(4)
 * @property {number} ms_08 개인매수(12)
 * @property {number} md_08 개인매도(12)
 * @property {number} rate_08 개인증감(12)
 * @property {number} svolume_08 개인순매수(12)
 * @property {string} jjcode_17 외국인투자자코드(4)
 * @property {number} ms_17 외국인매수(12)
 * @property {number} md_17 외국인매도(12)
 * @property {number} rate_17 외국인증감(12)
 * @property {number} svolume_17 외국인순매수(12)
 * @property {string} jjcode_18 기관계투자자코드(4)
 * @property {number} ms_18 기관계매수(12)
 * @property {number} md_18 기관계매도(12)
 * @property {number} rate_18 기관계증감(12)
 * @property {number} svolume_18 기관계순매수(12)
 * @property {string} jjcode_01 증권투자자코드(4)
 * @property {number} ms_01 증권매수(12)
 * @property {number} md_01 증권매도(12)
 * @property {number} rate_01 증권증감(12)
 * @property {number} svolume_01 증권순매수(12)
 * @property {string} jjcode_03 투신투자자코드(4)
 * @property {number} ms_03 투신매수(12)
 * @property {number} md_03 투신매도(12)
 * @property {number} rate_03 투신증감(12)
 * @property {number} svolume_03 투신순매수(12)
 * @property {string} jjcode_04 은행투자자코드(4)
 * @property {number} ms_04 은행매수(12)
 * @property {number} md_04 은행매도(12)
 * @property {number} rate_04 은행증감(12)
 * @property {number} svolume_04 은행순매수(12)
 * @property {string} jjcode_02 보험투자자코드(4)
 * @property {number} ms_02 보험매수(12)
 * @property {number} md_02 보험매도(12)
 * @property {number} rate_02 보험증감(12)
 * @property {number} svolume_02 보험순매수(12)
 * @property {string} jjcode_05 종금투자자코드(4)
 * @property {number} ms_05 종금매수(12)
 * @property {number} md_05 종금매도(12)
 * @property {number} rate_05 종금증감(12)
 * @property {number} svolume_05 종금순매수(12)
 * @property {string} jjcode_06 기금투자자코드(4)
 * @property {number} ms_06 기금매수(12)
 * @property {number} md_06 기금매도(12)
 * @property {number} rate_06 기금증감(12)
 * @property {number} svolume_06 기금순매수(12)
 * @property {string} jjcode_11 국가투자코드(4)
 * @property {number} ms_11 국가매수(12)
 * @property {number} md_11 국가매도(12)
 * @property {number} rate_11 국가증감(12)
 * @property {number} svolume_11 국가순매수(12)
 * @property {string} jjcode_07 기타투자자코드(4)
 * @property {number} ms_07 기타매수(12)
 * @property {number} md_07 기타매도(12)
 * @property {number} rate_07 기타증감(12)
 * @property {number} svolume_07 기타순매수(12)
 * @property {string} jjcode_00 사모펀드투자자코드(4)
 * @property {number} ms_00 사모펀드매수(12)
 * @property {number} md_00 사모펀드매도(12)
 * @property {number} rate_00 사모펀드증감(12)
 * @property {number} svolume_00 사모펀드순매수(12)
 */
/**
 * @typedef {Object} t1601_OutBlock2 [주식] 투자자 - 투자자별종합 
 * @property {string} tjjcode_08 개인투자자코드(4)
 * @property {number} ms_08 개인매수(12)
 * @property {number} md_08 개인매도(12)
 * @property {number} rate_08 개인증감(12)
 * @property {number} svolume_08 개인순매수(12)
 * @property {string} jjcode_17 외국인투자자코드(4)
 * @property {number} ms_17 외국인매수(12)
 * @property {number} md_17 외국인매도(12)
 * @property {number} rate_17 외국인증감(12)
 * @property {number} svolume_17 외국인순매수(12)
 * @property {string} jjcode_18 기관계투자자코드(4)
 * @property {number} ms_18 기관계매수(12)
 * @property {number} md_18 기관계매도(12)
 * @property {number} rate_18 기관계증감(12)
 * @property {number} svolume_18 기관계순매수(12)
 * @property {string} jjcode_01 증권투자자코드(4)
 * @property {number} ms_01 증권매수(12)
 * @property {number} md_01 증권매도(12)
 * @property {number} rate_01 증권증감(12)
 * @property {number} svolume_01 증권순매수(12)
 * @property {string} jjcode_03 투신투자자코드(4)
 * @property {number} ms_03 투신매수(12)
 * @property {number} md_03 투신매도(12)
 * @property {number} rate_03 투신증감(12)
 * @property {number} svolume_03 투신순매수(12)
 * @property {string} jjcode_04 은행투자자코드(4)
 * @property {number} ms_04 은행매수(12)
 * @property {number} md_04 은행매도(12)
 * @property {number} rate_04 은행증감(12)
 * @property {number} svolume_04 은행순매수(12)
 * @property {string} jjcode_02 보험투자자코드(4)
 * @property {number} ms_02 보험매수(12)
 * @property {number} md_02 보험매도(12)
 * @property {number} rate_02 보험증감(12)
 * @property {number} svolume_02 보험순매수(12)
 * @property {string} jjcode_05 종금투자자코드(4)
 * @property {number} ms_05 종금매수(12)
 * @property {number} md_05 종금매도(12)
 * @property {number} rate_05 종금증감(12)
 * @property {number} svolume_05 종금순매수(12)
 * @property {string} jjcode_06 기금투자자코드(4)
 * @property {number} ms_06 기금매수(12)
 * @property {number} md_06 기금매도(12)
 * @property {number} rate_06 기금증감(12)
 * @property {number} svolume_06 기금순매수(12)
 * @property {string} jjcode_11 국가투자코드(4)
 * @property {number} ms_11 국가매수(12)
 * @property {number} md_11 국가매도(12)
 * @property {number} rate_11 국가증감(12)
 * @property {number} svolume_11 국가순매수(12)
 * @property {string} jjcode_07 기타투자자코드(4)
 * @property {number} ms_07 기타매수(12)
 * @property {number} md_07 기타매도(12)
 * @property {number} rate_07 기타증감(12)
 * @property {number} svolume_07 기타순매수(12)
 * @property {string} jjcode_00 사모펀드투자자코드(4)
 * @property {number} ms_00 사모펀드매수(12)
 * @property {number} md_00 사모펀드매도(12)
 * @property {number} rate_00 사모펀드증감(12)
 * @property {number} svolume_00 사모펀드순매수(12)
 */
/**
 * @typedef {Object} t1601_OutBlock3 [주식] 투자자 - 투자자별종합 
 * @property {string} tjjcode_08 개인투자자코드(4)
 * @property {number} ms_08 개인매수(12)
 * @property {number} md_08 개인매도(12)
 * @property {number} rate_08 개인증감(12)
 * @property {number} svolume_08 개인순매수(12)
 * @property {string} jjcode_17 외국인투자자코드(4)
 * @property {number} ms_17 외국인매수(12)
 * @property {number} md_17 외국인매도(12)
 * @property {number} rate_17 외국인증감(12)
 * @property {number} svolume_17 외국인순매수(12)
 * @property {string} jjcode_18 기관계투자자코드(4)
 * @property {number} ms_18 기관계매수(12)
 * @property {number} md_18 기관계매도(12)
 * @property {number} rate_18 기관계증감(12)
 * @property {number} svolume_18 기관계순매수(12)
 * @property {string} jjcode_01 증권투자자코드(4)
 * @property {number} ms_01 증권매수(12)
 * @property {number} md_01 증권매도(12)
 * @property {number} rate_01 증권증감(12)
 * @property {number} svolume_01 증권순매수(12)
 * @property {string} jjcode_03 투신투자자코드(4)
 * @property {number} ms_03 투신매수(12)
 * @property {number} md_03 투신매도(12)
 * @property {number} rate_03 투신증감(12)
 * @property {number} svolume_03 투신순매수(12)
 * @property {string} jjcode_04 은행투자자코드(4)
 * @property {number} ms_04 은행매수(12)
 * @property {number} md_04 은행매도(12)
 * @property {number} rate_04 은행증감(12)
 * @property {number} svolume_04 은행순매수(12)
 * @property {string} jjcode_02 보험투자자코드(4)
 * @property {number} ms_02 보험매수(12)
 * @property {number} md_02 보험매도(12)
 * @property {number} rate_02 보험증감(12)
 * @property {number} svolume_02 보험순매수(12)
 * @property {string} jjcode_05 종금투자자코드(4)
 * @property {number} ms_05 종금매수(12)
 * @property {number} md_05 종금매도(12)
 * @property {number} rate_05 종금증감(12)
 * @property {number} svolume_05 종금순매수(12)
 * @property {string} jjcode_06 기금투자자코드(4)
 * @property {number} ms_06 기금매수(12)
 * @property {number} md_06 기금매도(12)
 * @property {number} rate_06 기금증감(12)
 * @property {number} svolume_06 기금순매수(12)
 * @property {string} jjcode_11 국가투자코드(4)
 * @property {number} ms_11 국가매수(12)
 * @property {number} md_11 국가매도(12)
 * @property {number} rate_11 국가증감(12)
 * @property {number} svolume_11 국가순매수(12)
 * @property {string} jjcode_07 기타투자자코드(4)
 * @property {number} ms_07 기타매수(12)
 * @property {number} md_07 기타매도(12)
 * @property {number} rate_07 기타증감(12)
 * @property {number} svolume_07 기타순매수(12)
 * @property {string} jjcode_00 사모펀드투자자코드(4)
 * @property {number} ms_00 사모펀드매수(12)
 * @property {number} md_00 사모펀드매도(12)
 * @property {number} rate_00 사모펀드증감(12)
 * @property {number} svolume_00 사모펀드순매수(12)
 */
/**
 * @typedef {Object} t1601_OutBlock4 [주식] 투자자 - 투자자별종합 
 * @property {string} tjjcode_08 개인투자자코드(4)
 * @property {number} ms_08 개인매수(12)
 * @property {number} md_08 개인매도(12)
 * @property {number} rate_08 개인증감(12)
 * @property {number} svolume_08 개인순매수(12)
 * @property {string} jjcode_17 외국인투자자코드(4)
 * @property {number} ms_17 외국인매수(12)
 * @property {number} md_17 외국인매도(12)
 * @property {number} rate_17 외국인증감(12)
 * @property {number} svolume_17 외국인순매수(12)
 * @property {string} jjcode_18 기관계투자자코드(4)
 * @property {number} ms_18 기관계매수(12)
 * @property {number} md_18 기관계매도(12)
 * @property {number} rate_18 기관계증감(12)
 * @property {number} svolume_18 기관계순매수(12)
 * @property {string} jjcode_01 증권투자자코드(4)
 * @property {number} ms_01 증권매수(12)
 * @property {number} md_01 증권매도(12)
 * @property {number} rate_01 증권증감(12)
 * @property {number} svolume_01 증권순매수(12)
 * @property {string} jjcode_03 투신투자자코드(4)
 * @property {number} ms_03 투신매수(12)
 * @property {number} md_03 투신매도(12)
 * @property {number} rate_03 투신증감(12)
 * @property {number} svolume_03 투신순매수(12)
 * @property {string} jjcode_04 은행투자자코드(4)
 * @property {number} ms_04 은행매수(12)
 * @property {number} md_04 은행매도(12)
 * @property {number} rate_04 은행증감(12)
 * @property {number} svolume_04 은행순매수(12)
 * @property {string} jjcode_02 보험투자자코드(4)
 * @property {number} ms_02 보험매수(12)
 * @property {number} md_02 보험매도(12)
 * @property {number} rate_02 보험증감(12)
 * @property {number} svolume_02 보험순매수(12)
 * @property {string} jjcode_05 종금투자자코드(4)
 * @property {number} ms_05 종금매수(12)
 * @property {number} md_05 종금매도(12)
 * @property {number} rate_05 종금증감(12)
 * @property {number} svolume_05 종금순매수(12)
 * @property {string} jjcode_06 기금투자자코드(4)
 * @property {number} ms_06 기금매수(12)
 * @property {number} md_06 기금매도(12)
 * @property {number} rate_06 기금증감(12)
 * @property {number} svolume_06 기금순매수(12)
 * @property {string} jjcode_11 국가투자코드(4)
 * @property {number} ms_11 국가매수(12)
 * @property {number} md_11 국가매도(12)
 * @property {number} rate_11 국가증감(12)
 * @property {number} svolume_11 국가순매수(12)
 * @property {string} jjcode_07 기타투자자코드(4)
 * @property {number} ms_07 기타매수(12)
 * @property {number} md_07 기타매도(12)
 * @property {number} rate_07 기타증감(12)
 * @property {number} svolume_07 기타순매수(12)
 * @property {string} jjcode_00 사모펀드투자자코드(4)
 * @property {number} ms_00 사모펀드매수(12)
 * @property {number} md_00 사모펀드매도(12)
 * @property {number} rate_00 사모펀드증감(12)
 * @property {number} svolume_00 사모펀드순매수(12)
 */
/**
 * @typedef {Object} t1601_OutBlock5 [주식] 투자자 - 투자자별종합 
 * @property {string} tjjcode_08 개인투자자코드(4)
 * @property {number} ms_08 개인매수(12)
 * @property {number} md_08 개인매도(12)
 * @property {number} rate_08 개인증감(12)
 * @property {number} svolume_08 개인순매수(12)
 * @property {string} jjcode_17 외국인투자자코드(4)
 * @property {number} ms_17 외국인매수(12)
 * @property {number} md_17 외국인매도(12)
 * @property {number} rate_17 외국인증감(12)
 * @property {number} svolume_17 외국인순매수(12)
 * @property {string} jjcode_18 기관계투자자코드(4)
 * @property {number} ms_18 기관계매수(12)
 * @property {number} md_18 기관계매도(12)
 * @property {number} rate_18 기관계증감(12)
 * @property {number} svolume_18 기관계순매수(12)
 * @property {string} jjcode_01 증권투자자코드(4)
 * @property {number} ms_01 증권매수(12)
 * @property {number} md_01 증권매도(12)
 * @property {number} rate_01 증권증감(12)
 * @property {number} svolume_01 증권순매수(12)
 * @property {string} jjcode_03 투신투자자코드(4)
 * @property {number} ms_03 투신매수(12)
 * @property {number} md_03 투신매도(12)
 * @property {number} rate_03 투신증감(12)
 * @property {number} svolume_03 투신순매수(12)
 * @property {string} jjcode_04 은행투자자코드(4)
 * @property {number} ms_04 은행매수(12)
 * @property {number} md_04 은행매도(12)
 * @property {number} rate_04 은행증감(12)
 * @property {number} svolume_04 은행순매수(12)
 * @property {string} jjcode_02 보험투자자코드(4)
 * @property {number} ms_02 보험매수(12)
 * @property {number} md_02 보험매도(12)
 * @property {number} rate_02 보험증감(12)
 * @property {number} svolume_02 보험순매수(12)
 * @property {string} jjcode_05 종금투자자코드(4)
 * @property {number} ms_05 종금매수(12)
 * @property {number} md_05 종금매도(12)
 * @property {number} rate_05 종금증감(12)
 * @property {number} svolume_05 종금순매수(12)
 * @property {string} jjcode_06 기금투자자코드(4)
 * @property {number} ms_06 기금매수(12)
 * @property {number} md_06 기금매도(12)
 * @property {number} rate_06 기금증감(12)
 * @property {number} svolume_06 기금순매수(12)
 * @property {string} jjcode_11 국가투자코드(4)
 * @property {number} ms_11 국가매수(12)
 * @property {number} md_11 국가매도(12)
 * @property {number} rate_11 국가증감(12)
 * @property {number} svolume_11 국가순매수(12)
 * @property {string} jjcode_07 기타투자자코드(4)
 * @property {number} ms_07 기타매수(12)
 * @property {number} md_07 기타매도(12)
 * @property {number} rate_07 기타증감(12)
 * @property {number} svolume_07 기타순매수(12)
 * @property {string} jjcode_00 사모펀드투자자코드(4)
 * @property {number} ms_00 사모펀드매수(12)
 * @property {number} md_00 사모펀드매도(12)
 * @property {number} rate_00 사모펀드증감(12)
 * @property {number} svolume_00 사모펀드순매수(12)
 */
/**
 * @typedef {Object} t1601_OutBlock6 [주식] 투자자 - 투자자별종합 
 * @property {string} tjjcode_08 개인투자자코드(4)
 * @property {number} ms_08 개인매수(12)
 * @property {number} md_08 개인매도(12)
 * @property {number} rate_08 개인증감(12)
 * @property {number} svolume_08 개인순매수(12)
 * @property {string} jjcode_17 외국인투자자코드(4)
 * @property {number} ms_17 외국인매수(12)
 * @property {number} md_17 외국인매도(12)
 * @property {number} rate_17 외국인증감(12)
 * @property {number} svolume_17 외국인순매수(12)
 * @property {string} jjcode_18 기관계투자자코드(4)
 * @property {number} ms_18 기관계매수(12)
 * @property {number} md_18 기관계매도(12)
 * @property {number} rate_18 기관계증감(12)
 * @property {number} svolume_18 기관계순매수(12)
 * @property {string} jjcode_01 증권투자자코드(4)
 * @property {number} ms_01 증권매수(12)
 * @property {number} md_01 증권매도(12)
 * @property {number} rate_01 증권증감(12)
 * @property {number} svolume_01 증권순매수(12)
 * @property {string} jjcode_03 투신투자자코드(4)
 * @property {number} ms_03 투신매수(12)
 * @property {number} md_03 투신매도(12)
 * @property {number} rate_03 투신증감(12)
 * @property {number} svolume_03 투신순매수(12)
 * @property {string} jjcode_04 은행투자자코드(4)
 * @property {number} ms_04 은행매수(12)
 * @property {number} md_04 은행매도(12)
 * @property {number} rate_04 은행증감(12)
 * @property {number} svolume_04 은행순매수(12)
 * @property {string} jjcode_02 보험투자자코드(4)
 * @property {number} ms_02 보험매수(12)
 * @property {number} md_02 보험매도(12)
 * @property {number} rate_02 보험증감(12)
 * @property {number} svolume_02 보험순매수(12)
 * @property {string} jjcode_05 종금투자자코드(4)
 * @property {number} ms_05 종금매수(12)
 * @property {number} md_05 종금매도(12)
 * @property {number} rate_05 종금증감(12)
 * @property {number} svolume_05 종금순매수(12)
 * @property {string} jjcode_06 기금투자자코드(4)
 * @property {number} ms_06 기금매수(12)
 * @property {number} md_06 기금매도(12)
 * @property {number} rate_06 기금증감(12)
 * @property {number} svolume_06 기금순매수(12)
 * @property {string} jjcode_11 국가투자코드(4)
 * @property {number} ms_11 국가매수(12)
 * @property {number} md_11 국가매도(12)
 * @property {number} rate_11 국가증감(12)
 * @property {number} svolume_11 국가순매수(12)
 * @property {string} jjcode_07 기타투자자코드(4)
 * @property {number} ms_07 기타매수(12)
 * @property {number} md_07 기타매도(12)
 * @property {number} rate_07 기타증감(12)
 * @property {number} svolume_07 기타순매수(12)
 * @property {string} jjcode_00 사모펀드투자자코드(4)
 * @property {number} ms_00 사모펀드매수(12)
 * @property {number} md_00 사모펀드매도(12)
 * @property {number} rate_00 사모펀드증감(12)
 * @property {number} svolume_00 사모펀드순매수(12)
 */
/**
 * [주식] 투자자 - 투자자별종합 (초당 2건 제한)
 * @param {string} gubun1 주식금액수량구분1(1) - 1:수량 2:금액
 * @param {string} gubun2 옵션금액수량구분2(1) - 1:수량 2:금액
 * @param {string} gubun3 금액단위(1) - 사용안함
 * @param {string} gubun4 선물금액수량구분4(1) - 1:수량 2:금액
 * @param {string} tr_cont 연속 거래 여부 [Y,N]
 * @param {string} tr_cont_key 연속일 경우 그전에 내려온 연속키 값 올림
 * @param {string} mac_address 	법인인 경우 필수 세팅
 * @returns {Promise<t1601|null>}  실패시 null 반환
 */
 exports.투자자별종합 = async(gubun1="",gubun2="",gubun3="",gubun4="",tr_cont="N",tr_cont_key="",mac_address="")=>{
    const header={
        "content-type":"application/json; charset=UTF-8",
        "authorization":await __ebestim.get_token(),
        "tr_cd":"t1601",
        "tr_cont":tr_cont,
        "tr_cont_key":tr_cont_key,
        "mac_address":mac_address
    }
    const body={
    "t1601InBlock":{
        "gubun1":gubun1,
        "gubun2":gubun2,
        "gubun3":gubun3,
        "gubun4":gubun4
       }
    }
  const result= await lib.http.post(__ebestim.url+"/stock/investor",header,body);
  if(result.status===200){
    return await result.json();
  }else{
    console.log(result.status+" - "+await result.text());
    return null;
  }
}