/**
 * @typedef {Object} NBT [주식] 실시간 시세 - (NXT)시간대별투자자매매추이
 * @property {string} tjjtime 수신시간(8)
 * @property {string} upcode 업종코드(3) 
 * @property {string} tjjcode0 투자자코드0(사모펀드)(8)
 * @property {string} msvolume0 매수거래량0(8) 
 * @property {string} mdvolume0 매도거래량0(8) 
 * @property {string} msvol0 거래량순매수0(8) 
 * @property {string} msvalue0 매수거래대금0(6) 
 * @property {string} mdvalue0 매도거래대금0(6) 
 * @property {string} msval0 거래대금순매수0(6) 
 * @property {string} tjjcode1 투자자코드1(개인)(8)
 * @property {string} msvolume1 매수거래량1(8) 
 * @property {string} mdvolume1 매도거래량1(8) 
 * @property {string} msvol1 거래량순매수1(8) 
 * @property {string} msvalue1 매수거래대금1(6) 
 * @property {string} mdvalue1 매도거래대금1(6) 
 * @property {string} msval1 거래대금순매수1(6) 
 * @property {string} tjjcode2 투자자코드2(외국인)(8)
 * @property {string} msvolume2 매수거래량2(8) 
 * @property {string} mdvolume2 매도거래량2(8) 
 * @property {string} msvol2 거래량순매수2(8) 
 * @property {string} msvalue2 매수거래대금2(6) 
 * @property {string} mdvalue2 매도거래대금2(6) 
 * @property {string} msval2 거래대금순매수2(6) 
 * @property {string} tjjcode3 투자자코드3(기관계)(8)
 * @property {string} msvolume3 매수거래량3(8) 
 * @property {string} mdvolume3 매도거래량3(8) 
 * @property {string} msvol3 거래량순매수3(8) 
 * @property {string} msvalue3 매수거래대금3(6) 
 * @property {string} mdvalue3 매도거래대금3(6) 
 * @property {string} msval3 거래대금순매수3(6) 
 * @property {string} tjjcode4 투자자코드4(증권)(8)
 * @property {string} msvolume4 매수거래량4(8) 
 * @property {string} mdvolume4 매도거래량4(8) 
 * @property {string} msvol4 거래량순매수4(8) 
 * @property {string} msvalue4 매수거래대금4(6) 
 * @property {string} mdvalue4 매도거래대금4(6) 
 * @property {string} msval4 거래대금순매수4(6) 
 * @property {string} tjjcode5 투자자코드5(투신)(8)
 * @property {string} msvolume5 매수거래량5(8) 
 * @property {string} mdvolume5 매도거래량5(8) 
 * @property {string} msvol5 거래량순매수5(8) 
 * @property {string} msvalue5 매수거래대금5(6) 
 * @property {string} mdvalue5 매도거래대금5(6) 
 * @property {string} msval5 거래대금순매수5(6) 
 * @property {string} tjjcode6 투자자코드6(은행)(8)
 * @property {string} msvolume6 매수거래량6(8) 
 * @property {string} mdvolume6 매도거래량6(8) 
 * @property {string} msvol6 거래량순매수6(8) 
 * @property {string} msvalue6 매수거래대금6(6) 
 * @property {string} mdvalue6 매도거래대금6(6) 
 * @property {string} msval6 거래대금순매수6(6) 
 * @property {string} tjjcode7 투자자코드7(보험)(8)
 * @property {string} msvolume7 매수거래량7(8) 
 * @property {string} mdvolume7 매도거래량7(8) 
 * @property {string} msvol7 거래량순매수7(8) 
 * @property {string} msvalue7 매수거래대금7(6) 
 * @property {string} mdvalue7 매도거래대금7(6) 
 * @property {string} msval7 거래대금순매수7(6) 
 * @property {string} tjjcode8 투자자코드8(종금)(8)
 * @property {string} msvolume8 매수거래량8(8) 
 * @property {string} mdvolume8 매도거래량8(8) 
 * @property {string} msvol8 거래량순매수8(8) 
 * @property {string} msvalue8 매수거래대금8(6) 
 * @property {string} mdvalue8 매도거래대금8(6) 
 * @property {string} msval8 거래대금순매수8(6) 
 * @property {string} tjjcode9 투자자코드9(기금)(8)
 * @property {string} msvolume9 매수거래량9(8) 
 * @property {string} mdvolume9 매도거래량9(8) 
 * @property {string} msvol9 거래량순매수9(8) 
 * @property {string} msvalue9 매수거래대금9(6) 
 * @property {string} mdvalue9 매도거래대금9(6) 
 * @property {string} msval9 거래대금순매수9(6) 
 * @property {string} tjjcode10 투자자코드10(선물업자)(8)
 * @property {string} msvolume10 매수거래량10(8) 
 * @property {string} mdvolume10 매도거래량10(8) 
 * @property {string} msvol10 거래량순매수10(8) 
 * @property {string} msvalue10 매수거래대금10(6) 
 * @property {string} mdvalue10 매도거래대금10(6) 
 * @property {string} msval10 거래대금순매수10(6) 
 * @property {string} tjjcode11 투자자코드11(기타)(8)
 * @property {string} msvolume11 매수거래량11(8) 
 * @property {string} mdvolume11 매도거래량11(8) 
 * @property {string} msvol11 거래량순매수11(8) 
 * @property {string} msvalue11 매수거래대금11(6) 
 * @property {string} mdvalue11 매도거래대금11(6) 
 * @property {string} msval11 거래대금순매수11(6) 
 * @property {string} ex_upcode 거래소별업종코드(4) 
*/
/** @typedef {(data:NBT)=>void} NBTFunc*/
/**
 * [주식] 실시간 시세 - (NXT)시간대별투자자매매추이
 * @param {string} tr_key 거래소별업종코드(4) N+업종코드(3), (계좌등록/해제 일 경우 빈 문자열)
 * @param {NBTFunc} recv 서버에서 데이터 받으면 해당 함수 호출
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
exports.등록 = async(tr_key="",recv)=>{
    return await __ebestim.realadd("NBT",tr_key,recv);
}
/**
 * [주식] 실시간 시세 - (NXT)시간대별투자자매매추이 실시간 등록 해제
 * @param {string} tr_key 실시간 등록시 입력했던 키값
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
 exports.해제 = async(tr_key)=>{
    return await __ebestim.realdel("NBT",tr_key);
}
