/**
 * @typedef {Object} SC0 [주식] 실시간 시세 - 주식주문접수
 * @property {string} spareordqty ex:"0"(?)
 * @property {string} trcode ex:"SONAT000"(?)
 * @property {string} userid ex:"hdkrggg4"(?)
 * @property {string} dummy ex:""(?)
 * @property {string} len ex:"1053"(?)
 * @property {string} loandt ex:"00000000"(?)
 * @property {string} orgordmdfyqty ex:"0"(?)
 * @property {string} avrpchsprc ex:".00"(?)
 * @property {string} cont ex:"N"(?)
 * @property {string} hname ex:"삼성전자"(?)
 * @property {string} pgmtype ex:"0"(?)
 * @property {string} compress ex:"0"(?)
 * @property {string} ordprice ex:"60000"(?)
 * @property {string} procgb ex:"0"(?)
 * @property {string} unercsellordqty ex:"0"(?)
 * @property {string} ruseableamt ex:"0"(?)
 * @property {string} ordgb ex:"02"(?)
 * @property {string} gubun ex:"B"(?)
 * @property {string} trid ex:"2000095635771500"(?)
 * @property {string} flctqty ex:"0"(?)
 * @property {string} varmsglen ex:"0"(?)
 * @property {string} ordno ex:"86382"(?)
 * @property {string} passwd ex:"********"(?)
 * @property {string} singb ex:"000"(?)
 * @property {string} gmhogayn ex:"0"(?)
 * @property {string} ordruseqty ex:"0"(?)
 * @property {string} deposit ex:"79759964"(?)
 * @property {string} trsrc ex:"L"(?)
 * @property {string} gmhogagb ex:"0"(?)
 * @property {string} reqcnt ex:" "(?)
 * @property {string} accno1 ex:"20011132702"(?)
 * @property {string} strtgcode ex:""(?)
 * @property {string} ordchegb ex:"01"(?)
 * @property {string} ordtm ex:"095636020"(?)
 * @property {string} orduserid ex:"hdkrggg4"(?)
 * @property {string} ordseqno ex:"0"(?)
 * @property {string} ordablesubstamt ex:"244160"(?)
 * @property {string} pchsamt ex:"0"(?)
 * @property {string} encrypt ex:"0"(?)
 * @property {string} accno2 ex:""(?)
 * @property {string} shtcode ex:"A005930"(?)
 * @property {string} contkey ex:"0"(?)
 * @property {string} brwmgmyn ex:"0"(?)
 * @property {string} seq ex:"000000154"(?)
 * @property {string} mtordseqno ex:"0"(?)
 * @property {string} lineseq ex:"200000001"(?)
 * @property {string} tongsingb ex:"40"(?)
 * @property {string} varlen ex:"50"(?)
 * @property {string} lpgb ex:"0"(?)
 * @property {string} rsvordno ex:"0"(?)
 * @property {string} spotordqty ex:"0"(?)
 * @property {string} cvrgseqno ex:"0"(?)
 * @property {string} filler ex:""(?)
 * @property {string} hogagb ex:"0"(?)
 * @property {string} secbalqty ex:"0"(?)
 * @property {string} expcode ex:"KR7005930003"(?)
 * @property {string} prntordno ex:"86382"(?)
 * @property {string} ordablemny ex:"79459964"(?)
 * @property {string} pubip ex:"010130001138"(?)
 * @property {string} prvip ex:""(?)
 * @property {string} funckey ex:"C"(?)
 * @property {string} accno ex:"20011132702"(?)
 * @property {string} compreq ex:"0"(?)
 * @property {string} orgordundrqty ex:"0"(?)
 * @property {string} ruseordamt ex:"0"(?)
 * @property {string} crdtpldgruseamt ex:" "(?)
 * @property {string} ordordcancelqty ex:"0"(?)
 * @property {string} ordamt ex:"120000"(?)
 * @property {string} spareordno ex:"0"(?)
 * @property {string} termno ex:""(?)
 * @property {string} etfhogagb ex:"00"(?)
 * @property {string} bpno ex:"106"(?)
 * @property {string} substamt ex:"244160"(?)
 * @property {string} mgempno ex:"999999106"(?)
 * @property {string} csgnsubstmgn ex:"0"(?)
 * @property {string} offset ex:"212"(?)
 * @property {string} sellableqty ex:"0"(?)
 * @property {string} groupid ex:""(?)
 * @property {string} varhdlen ex:"0"(?)
 * @property {string} mnyordamt ex:"120000"(?)
 * @property {string} itemno ex:"0"(?)
 * @property {string} prtno ex:"0"(?)
 * @property {string} marketgb ex:"10"(?)
 * @property {string} ifinfo ex:""(?)
 * @property {string} ordableruseqty ex:"0"(?)
 * @property {string} crdtuseamt ex:"0"(?)
 * @property {string} ordcmsnamt ex:"0"(?)
 * @property {string} secbalqtyd2 ex:"0"(?)
 * @property {string} eventid ex:""(?)
 * @property {string} csgnmnymgn ex:"300000"(?)
 * @property {string} pcbpno ex:"000"(?)
 * @property {string} orgordno ex:"0"(?)
 * @property {string} basketno ex:"0"(?)
 * @property {string} ifid ex:"000"(?)
 * @property {string} media ex:"HT"(?)
 * @property {string} filler1 ex:""(?)
 * @property {string} mbrno ex:"63"(?)
 * @property {string} proctm ex:"95636020"(?)
 * @property {string} ordsubstamt ex:"0"(?)
 * @property {string} lang ex:"K"(?)
 * @property {string} spotordableqty ex:"0"(?)
 * @property {string} cvrgordtp ex:"0"(?)
 * @property {string} ordqty ex:"2"(?)
 * @property {string} outgu ex:""(?)
 * @property {string} msgcode ex:"0040"(?)
 * @property {string} futaccno ex:"00000000000000000000"(?)
 * @property {string} futmarketgb ex:"0"(?)
 * @property {string} admbrchno ex:"106"(?)
 * @property {string} comid ex:"063"(?)
 * @property {string} bnstp ex:"2"(?)
 * @property {string} user ex:"hdkrggg4"(?)
 * @property {string} nmcpysndno ex:"0"(?) 
*/
/** @typedef {(data:SC0)=>void} SC0Func*/
/**
 * [주식] 실시간 시세 - 주식주문접수
 * @param {string} tr_key 단축코드 6자리 또는 8자리 (단건, 연속), (계좌등록/해제 일 경우 빈 문자열)
 * @param {SC0Func} recv 서버에서 데이터 받으면 해당 함수 호출
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
 exports.등록 = async(tr_key="",recv)=>{
    return await __ebestim.realadd("SC0",tr_key,recv);
}
/**
 * [주식] 실시간 시세 - 주식주문접수 실시간 등록 해제
 * @param {string} tr_key 실시간 등록시 입력했던 키값
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
 exports.해제 = async(tr_key)=>{
    return await __ebestim.realdel("SC0",tr_key);
}
