/**
 * @typedef {Object} SC3 [주식] 실시간 시세 - 주식주문취소
 * @property {string} trchno ex:"0"(?)
 * @property {string} trtzxLevytp ex:"0"(?)
 * @property {string} ordtrxptncode ex:"0"(?)
 * @property {string} acntnm ex:"우우돌"(?)
 * @property {string} trcode ex:"SONAS100"(?)
 * @property {string} userid ex:"hdkrggg4"(?)
 * @property {string} agrgbrnno ex:"106"(?)
 * @property {string} regmktcode ex:"10"(?)
 * @property {string} len ex:"1294"(?)
 * @property {string} opdrtnno ex:"0"(?)
 * @property {string} orgordmdfyqty ex:"0"(?)
 * @property {string} avrpchsprc ex:"0"(?)
 * @property {string} exectime ex:"150622765"(?)
 * @property {string} cont ex:"N"(?)
 * @property {string} mnymgnrat ex:".000"(?)
 * @property {string} mdfycnfqty ex:"0"(?)
 * @property {string} orgordcancqty ex:"1"(?)
 * @property {string} compress ex:"0"(?)
 * @property {string} execprc ex:"0"(?)
 * @property {string} mdfycnfprc ex:"0"(?)
 * @property {string} unercsellordqty ex:"0"(?)
 * @property {string} cmsnamtexecamt ex:"0"(?)
 * @property {string} ruseableamt ex:"0"(?)
 * @property {string} gubun ex:"B"(?)
 * @property {string} trid ex:"4000150622737537"(?)
 * @property {string} flctqty ex:"0"(?)
 * @property {string} execno ex:"0"(?)
 * @property {string} lptp ex:"0"(?)
 * @property {string} varmsglen ex:"0"(?)
 * @property {string} ordno ex:"88343"(?)
 * @property {string} futsmkttp ex:""(?)
 * @property {string} crdtexecamt ex:"0"(?)
 * @property {string} deposit ex:"78489774"(?)
 * @property {string} frgrunqno ex:"000000"(?)
 * @property {string} crdayruseexecval ex:"0"(?)
 * @property {string} trsrc ex:"L"(?)
 * @property {string} ordacntno ex:"20011132702"(?)
 * @property {string} reqcnt ex:" "(?)
 * @property {string} shtnIsuno ex:"A000020"(?)
 * @property {string} accno1 ex:"20011132702"(?)
 * @property {string} strtgcode ex:""(?)
 * @property {string} ordseqno ex:"0"(?)
 * @property {string} Isunm ex:"동화약품"(?)
 * @property {string} ordablesubstamt ex:"1260000"(?)
 * @property {string} encrypt ex:"0"(?)
 * @property {string} Isuno ex:"KR7000020008"(?)
 * @property {string} accno2 ex:""(?)
 * @property {string} contkey ex:"0"(?)
 * @property {string} Loandt ex:"00000000"(?)
 * @property {string} seq ex:"000000009"(?)
 * @property {string} lineseq ex:"200000012"(?)
 * @property {string} varlen ex:"50"(?)
 * @property {string} orduserId ex:"hdkrggg4"(?)
 * @property {string} mgmtbrnno ex:"106"(?)
 * @property {string} rjtqty ex:"0"(?)
 * @property {string} ordprcptncode ex:"00"(?)
 * @property {string} stdIsuno ex:"KR7000020008"(?)
 * @property {string} pchsant ex:"0"(?)
 * @property {string} filler ex:""(?)
 * @property {string} secbalqty ex:"0"(?)
 * @property {string} ordxctptncode ex:"13"(?)
 * @property {string} canccnfqty ex:"1"(?)
 * @property {string} ordablemny ex:"78173174"(?)
 * @property {string} pubip ex:"010130001138"(?)
 * @property {string} prvip ex:""(?)
 * @property {string} funckey ex:"C"(?)
 * @property {string} accno ex:"20011132702"(?)
 * @property {string} compreq ex:"0"(?)
 * @property {string} crdtpldgruseamt ex:"0"(?)
 * @property {string} ordamt ex:"9500"(?)
 * @property {string} termno ex:""(?)
 * @property {string} crdtpldgexecamt ex:"0"(?)
 * @property {string} ordcndi ex:"0"(?)
 * @property {string} rmndLoanamt ex:"0"(?)
 * @property {string} bpno ex:"106"(?)
 * @property {string} substamt ex:"1302000"(?)
 * @property {string} mgempno ex:"999999106"(?)
 * @property {string} csgnsubstmgn ex:"42000"(?)
 * @property {string} offset ex:"212"(?)
 * @property {string} rcptexectime ex:"150622765"(?)
 * @property {string} sellableqty ex:"0"(?)
 * @property {string} spotexecqty ex:"0"(?)
 * @property {string} varhdlen ex:"0"(?)
 * @property {string} substmgnrat ex:".3000000"(?)
 * @property {string} ordavrexecprc ex:"0"(?)
 * @property {string} itemno ex:"0"(?)
 * @property {string} mgntrncode ex:"000"(?)
 * @property {string} nsavtrdqty ex:"0"(?)
 * @property {string} ifinfo ex:""(?)
 * @property {string} ordableruseqty ex:"0"(?)
 * @property {string} ptflno ex:"0"(?)
 * @property {string} secbalqtyd2 ex:"0"(?)
 * @property {string} brwmgmtYn ex:"0"(?)
 * @property {string} eventid ex:""(?)
 * @property {string} csgnmnymgn ex:"316600"(?)
 * @property {string} pcbpno ex:"000"(?)
 * @property {string} orgordno ex:"88342"(?)
 * @property {string} ifid ex:"000"(?)
 * @property {string} media ex:"HT"(?)
 * @property {string} mtiordseqno ex:"0"(?)
 * @property {string} filler1 ex:""(?)
 * @property {string} orgordunercqty ex:"5"(?)
 * @property {string} mbrnmbrno ex:"0"(?)
 * @property {string} futsLnkbrnno ex:""(?)
 * @property {string} commdacode ex:"40"(?)
 * @property {string} stslexecqty ex:"0"(?)
 * @property {string} proctm ex:"150622765"(?)
 * @property {string} bfstdIsuno ex:"KR7000020008"(?)
 * @property {string} futsLnkacntno ex:""(?)
 * @property {string} lang ex:"K"(?)
 * @property {string} unercqty ex:"0"(?)
 * @property {string} execqty ex:"0"(?)
 * @property {string} adduptp ex:"40"(?)
 * @property {string} bskno ex:"0"(?)
 * @property {string} spotordableqty ex:"0"(?)
 * @property {string} ubstexecamt ex:"0"(?)
 * @property {string} cvrgordtp ex:"0"(?)
 * @property {string} ordqty ex:"1"(?)
 * @property {string} mnyexecamt ex:"0"(?)
 * @property {string} outgu ex:"1"(?)
 * @property {string} msgcode ex:"9999"(?)
 * @property {string} ordtrdptncode ex:"00"(?)
 * @property {string} ordmktcode ex:"10"(?)
 * @property {string} ordptncode ex:"02"(?)
 * @property {string} prdayruseexecval ex:"0"(?)
 * @property {string} comid ex:"063"(?)
 * @property {string} bnstp ex:"2"(?)
 * @property {string} user ex:"hdkrggg4"(?)
 * @property {string} ordprc ex:"0"(?) 
*/
/** @typedef {(data:SC3)=>void} SC3Func*/
/**
 * [주식] 실시간 시세 - 주식주문취소
 * @param {string} tr_key 단축코드 6자리 또는 8자리 (단건, 연속), (계좌등록/해제 일 경우 빈 문자열)
 * @param {SC3Func} recv 서버에서 데이터 받으면 해당 함수 호출
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
 exports.등록 = async(tr_key="",recv)=>{
    return await __ebestim.realadd("SC3",tr_key,recv);
}
/**
 * [주식] 실시간 시세 - 주식주문취소 실시간 등록 해제
 * @param {string} tr_key 실시간 등록시 입력했던 키값
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
 exports.해제 = async(tr_key)=>{
    return await __ebestim.realdel("SC3",tr_key);
}
