/**
 * @typedef {Object} UH1 [주식] 실시간 시세 - (통합)호가잔량
 * @property {string} hotime 호가시간(6)
 * @property {string} offerho1 매도호가1(7)
 * @property {string} bidho1 매수호가1(7)
 * @property {string} krx_offerrem1 KRX매도호가잔량1(9)
 * @property {string} krx_bidrem1 KRX매수호가잔량1(9)
 * @property {string} nxt_offerrem1 NXT매도호가잔량1(9)
 * @property {string} nxt_bidrem1 NXT매수호가잔량1(9)
 * @property {string} unt_offerrem1 통합매도호가잔량1(9)
 * @property {string} unt_bidrem1 통합매수호가잔량1(9)
 * @property {string} offerho2 매도호가2(7)
 * @property {string} bidho2 매수호가2(7)
 * @property {string} krx_offerrem2 KRX매도호가잔량2(9)
 * @property {string} krx_bidrem2 KRX매수호가잔량2(9)
 * @property {string} nxt_offerrem2 NXT매도호가잔량2(9)
 * @property {string} nxt_bidrem2 NXT매수호가잔량2(9)
 * @property {string} unt_offerrem2 통합매도호가잔량2(9)
 * @property {string} unt_bidrem2 통합매수호가잔량2(9)
 * @property {string} offerho3 매도호가3(7)
 * @property {string} bidho3 매수호가3(7)
 * @property {string} krx_offerrem3 KRX매도호가잔량3(9)
 * @property {string} krx_bidrem3 KRX매수호가잔량3(9)
 * @property {string} nxt_offerrem3 NXT매도호가잔량3(9)
 * @property {string} nxt_bidrem3 NXT매수호가잔량3(9)
 * @property {string} unt_offerrem3 통합매도호가잔량3(9)
 * @property {string} unt_bidrem3 통합매수호가잔량3(9)
 * @property {string} offerho4 매도호가4(7)
 * @property {string} bidho4 매수호가4(7)
 * @property {string} krx_offerrem4 KRX매도호가잔량4(9)
 * @property {string} krx_bidrem4 KRX매수호가잔량4(9)
 * @property {string} nxt_offerrem4 NXT매도호가잔량4(9)
 * @property {string} nxt_bidrem4 NXT매수호가잔량4(9)
 * @property {string} unt_offerrem4 통합매도호가잔량4(9)
 * @property {string} unt_bidrem4 통합매수호가잔량4(9)
 * @property {string} offerho5 매도호가5(7)
 * @property {string} bidho5 매수호가5(7)
 * @property {string} krx_offerrem5 KRX매도호가잔량5(9)
 * @property {string} krx_bidrem5 KRX매수호가잔량5(9)
 * @property {string} nxt_offerrem5 NXT매도호가잔량5(9)
 * @property {string} nxt_bidrem5 NXT매수호가잔량5(9)
 * @property {string} unt_offerrem5 통합매도호가잔량5(9)
 * @property {string} unt_bidrem5 통합매수호가잔량5(9)
 * @property {string} offerho6 매도호가6(7)
 * @property {string} bidho6 매수호가6(7)
 * @property {string} krx_offerrem6 KRX매도호가잔량6(9)
 * @property {string} krx_bidrem6 KRX매수호가잔량6(9)
 * @property {string} nxt_offerrem6 NXT매도호가잔량6(9)
 * @property {string} nxt_bidrem6 NXT매수호가잔량6(9)
 * @property {string} unt_offerrem6 통합매도호가잔량6(9)
 * @property {string} unt_bidrem6 통합매수호가잔량6(9)
 * @property {string} offerho7 매도호가7(7)
 * @property {string} bidho7 매수호가7(7)
 * @property {string} krx_offerrem7 KRX매도호가잔량7(9)
 * @property {string} krx_bidrem7 KRX매수호가잔량7(9)
 * @property {string} nxt_offerrem7 NXT매도호가잔량7(9)
 * @property {string} nxt_bidrem7 NXT매수호가잔량7(9)
 * @property {string} unt_offerrem7 통합매도호가잔량7(9)
 * @property {string} unt_bidrem7 통합매수호가잔량7(9)
 * @property {string} offerho8 매도호가8(7)
 * @property {string} bidho8 매수호가8(7)
 * @property {string} krx_offerrem8 KRX매도호가잔량8(9)
 * @property {string} krx_bidrem8 KRX매수호가잔량8(9)
 * @property {string} nxt_offerrem8 NXT매도호가잔량8(9)
 * @property {string} nxt_bidrem8 NXT매수호가잔량8(9)
 * @property {string} unt_offerrem8 통합매도호가잔량8(9)
 * @property {string} unt_bidrem8 통합매수호가잔량8(9)
 * @property {string} offerho9 매도호가9(7)
 * @property {string} bidho9 매수호가9(7)
 * @property {string} krx_offerrem9 KRX매도호가잔량9(9)
 * @property {string} krx_bidrem9 KRX매수호가잔량9(9)
 * @property {string} nxt_offerrem9 NXT매도호가잔량9(9)
 * @property {string} nxt_bidrem9 NXT매수호가잔량9(9)
 * @property {string} unt_offerrem9 통합매도호가잔량9(9)
 * @property {string} unt_bidrem9 통합매수호가잔량9(9)
 * @property {string} offerho10 매도호가10(7)
 * @property {string} bidho10 매수호가10(7)
 * @property {string} krx_offerrem10 KRX매도호가잔량10(9)
 * @property {string} krx_bidrem10 KRX매수호가잔량10(9)
 * @property {string} nxt_offerrem10 NXT매도호가잔량10(9)
 * @property {string} nxt_bidrem10 NXT매수호가잔량10(9)
 * @property {string} unt_offerrem10 통합매도호가잔량10(9)
 * @property {string} unt_bidrem10 통합매수호가잔량10(9)
 * @property {string} krx_totofferrem KRX총매도호가잔량(9)
 * @property {string} krx_totbidrem KRX총매수호가잔량(9)
 * @property {string} nxt_totofferrem NXT총매도호가잔량(9)
 * @property {string} nxt_totbidrem NXT총매수호가잔량(9)
 * @property {string} unt_totofferrem 통합총매도호가잔량(9)
 * @property {string} unt_totbidrem 통합총매수호가잔량(9)
 * @property {string} krx_donsigubun KRX동시호가구분(1)
 * @property {string} nxt_donsigubun NXT동시호가구분(1)
 * @property {string} shcode 단축코드(6)
 * @property {string} alloc_gubun 배분적용구분(1)
 * @property {string} volume 누적거래량(12) 
 * @property {number} krx_midprice KRX중간가격(8)
 * @property {number} krx_offermidsumrem KRX매도중간가잔량합계수량(9)
 * @property {number} krx_bidmidsumrem KRX매수중간가잔량합계수량(9)
 * @property {number} nxt_midprice NXT중간가격(8)
 * @property {number} nxt_offermidsumrem NXT매도중간가잔량합계수량(9)
 * @property {number} nxt_bidmidsumrem NXT매수중간가잔량합계수량(9)
 * @property {number} krx_midsumrem KRX중간가잔량합계수량(9)
 * @property {number} krx_midsumremgubun KRX중간가잔량구분(1)''없음 '1'매도 '2'매수
 * @property {number} nxt_midsumrem NXT중간가잔량합계수량(9)
 * @property {number} nxt_midsumremgubun NXT중간가잔량구분(1)''없음 '1'매도 '2'매수
 * @property {string} ex_shcode 거래소별단축코드(10)
*/
/** @typedef {(data:UH1)=>void} UH1Func*/
/**
 * [주식] 실시간 시세 - (통합)호가잔량
 * @param {string} tr_key 단축코드 7자리 + 공백 3자리(U+6자리코드), (계좌등록/해제 일 경우 빈 문자열)
 * @param {UH1Func} recv 서버에서 데이터 받으면 해당 함수 호출
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
exports.등록 = async(tr_key="",recv)=>{
    return await __ebestim.realadd("UH1",tr_key,recv);
}
/**
 * [주식] 실시간 시세 - (통합)호가잔량 실시간 등록 해제
 * @param {string} tr_key 실시간 등록시 입력했던 키값
 * @returns {Promise<boolean>}  실패, 성공 여부
 */
 exports.해제 = async(tr_key)=>{
    return await __ebestim.realdel("UH1",tr_key);
}
