
module.exports=(function(){
    Object.assign(this,require("./t1101.js"))
    Object.assign(this,require("./t1102.js"))
    Object.assign(this,require("./t1104.js"))
    Object.assign(this,require("./t1105.js"))
    Object.assign(this,require("./t1109.js"))
    Object.assign(this,require("./t1301.js"))
    Object.assign(this,require("./t1302.js"))
    Object.assign(this,require("./t1305.js"))
    Object.assign(this,require("./t1308.js"))
    Object.assign(this,require("./t1310.js"))
    Object.assign(this,require("./t1404.js"))
    Object.assign(this,require("./t1405.js"))
    Object.assign(this,require("./t1410.js"))
    Object.assign(this,require("./t1422.js"))
    Object.assign(this,require("./t1427.js"))
    Object.assign(this,require("./t1442.js"))
    Object.assign(this,require("./t1449.js"))
    Object.assign(this,require("./t1471.js"))
    Object.assign(this,require("./t1475.js"))
    Object.assign(this,require("./t1486.js"))
    Object.assign(this,require("./t1488.js"))
    Object.assign(this,require("./t8407.js"))
    Object.assign(this,require("./t9945.js"))
    return this;
})();