
module.exports=(function(){
    this.주식현재가호가조회=require("./t1101.js")
    this.주식현재가_시세조회=require("./t1102.js")
    this.주식현재가시세메모=require("./t1104.js")
    this.주식피봇_디마크조회=require("./t1105.js")
    this.시간외체결량=require("./t1109.js")
    this.주식시간대별체결조회=require("./t1301.js")
    this.주식분별주가조회=require("./t1302.js")
    this.기간별주가=require("./t1305.js")
    this.주식시간대별체결조회챠트=require("./t1308.js")
    this.주식당일전일분틱조회=require("./t1310.js")
    this.관리_불성실_투자유의조회=require("./t1404.js")
    this.투자경고_매매정지_정리매매조회=require("./t1405.js")
    this.초저유동성조회=require("./t1410.js")
    this.상_하한=require("./t1422.js")
    this.상_하한가직전=require("./t1427.js")
    this.신고_신저가=require("./t1442.js")
    this.가격대별매매비중조회=require("./t1449.js")
    this.시간대별호가잔량추이=require("./t1471.js")
    this.체결강도추이=require("./t1475.js")
    this.시간별예상체결가=require("./t1486.js")
    this.예상체결가등락율상위조회=require("./t1488.js")
    this.API용주식멀티현재가조회=require("./t8407.js")
    this.주식마스터조회API용=require("./t9945.js")
    return this;
})();